include:
  - ./jitsi-meet/docker-compose.yml

services:
  app:
    build: ./webapp
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
