version: "2"
services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - ./:/home/node/app
    ports:
      - "192.168.1.3:80:3000"
    command: "node ./.output/server/index.mjs"
